#!/bin/sh
# Load nvm and use the correct Node version
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
# nvm use 22 or whatever version you want

npx pnpm format
npx pnpm lint --fix
